services:
  app:
    image: app-dfo
    container_name: app-dfo
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on: 
      - dfo
    networks:
      - dfo_net
  dfo:
    image: dfo
    container_name: dfo
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - dfo_net
    depends_on:
      - redis
  redis:
    image: redis/redis-stack:latest
    container_name: redis_cache
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
      - ${REDIS_HTTP_PORT}:8001
    networks:
      - dfo_net
    volumes:
      - /data/dfo/redis-stack:/data
    restart: unless-stopped

networks:
  dfo_net:
    name: dfo_net
    driver: bridge