FROM node:20.12.2

WORKDIR /app

COPY ./frontend/package.json /app/package.json
COPY ./frontend/package-lock.json /app/package-lock.json

RUN npm install

COPY ./frontend/public /app/public
COPY ./frontend/src /app/src

CMD ["npm", "start"]
